---
# deploy/master/docker-compose.yml
# Define the version of the compose file we're using
version: '2'

# Define our services
services:
  # Jenkins master's configuration
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - 'jenkins_home:/var/jenkins_home'
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins_home:
    driver: local